apiVersion: v1
data:
  as-config.json: |
    {
        "work_dir": "/opt/confidential-containers/attestation-service",
        "policy_engine": "opa",
        "rvps_store_type": "LocalFs",
        "rvps_config": {
            "remote_addr":"http://127.0.0.1:50003"
        },
        "attestation_token_broker": "Simple",
        "attestation_token_config": {
          "duration_min": 5
        }
    }
kind: ConfigMap
metadata:
  name: as-config-grpc-sample
