apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: trustee-operator
    app.kubernetes.io/part-of: trustee-operator
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Values.namePrefix }}leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.namePrefix }}leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.namePrefix }}controller-manager
  namespace: {{ .Values.namespace }}
