apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: manager-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: trustee-operator
    app.kubernetes.io/part-of: trustee-operator
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Values.namePrefix }}manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.namePrefix }}manager-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.namePrefix }}controller-manager
  namespace: {{ .Values.namespace }}
