# permissions for end users to view trusteeconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: trusteeconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: trustee-operator
    app.kubernetes.io/part-of: trustee-operator
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Values.namePrefix }}trusteeconfig-viewer-role
rules:
- apiGroups:
  - confidentialcontainers.org
  resources:
  - trusteeconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - confidentialcontainers.org
  resources:
  - trusteeconfigs/status
  verbs:
  - get
