apiVersion: v1
kind: ConfigMap
metadata:
  name: tdx-config
  namespace: kbs-operator-system
data:
  sgx_default_qcnl.conf: |
      {
        "collateral_service": "https://api.trustedservices.intel.com/sgx/certification/v4/",
        "pccs_url": "https://api.trustedservices.intel.com/sgx/certification/v4/"
        // "pccs_url": "https://localhost:8081/sgx/certification/v4/",
        // To accept insecure HTTPS certificate, set this option to false
        // "use_secure_cert": false
      }